<a href="https://colab.research.google.com/github/SubhashPSharma/Decision-Tree-Model/blob/main/Decision_Tree_Model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# It is a DecisionTreeRegressor Model

# Importing Libraries

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Load Dataset
botson = pd.read_csv('/content/Boston.csv')

In [ ]:
botson.head()

In [ ]:
# no need of columne Unnamed: 0, so we removed it
botson = botson.drop('Unnamed: 0', axis = 1)

In [ ]:
botson.head()

In the Dataset we take medv is the dependent variable and rm is the independent variable.

rm:- it stands for avg. number of rooms and

medv:- it stands for median price value of the house.

basically we study how does the median price value of the house change with respect to number of rooms, scatter plot will figure out.

In [ ]:
# Scatter
plt.scatter(x = botson['rm'], y = botson['medv'], color = 'brown')
plt.xlabel('Avg. no. of rooms per dwelling')
plt.ylabel('Median value of home')
plt.show()

We can see here if Avg. no. of room increase then Median price value of home also increase.

In [ ]:
# Getting the feature and the target
x = pd.DataFrame(botson['rm']) # feature
y = pd.DataFrame(botson['medv']) # target

In [ ]:
# Spiltting into train and test
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.20, random_state = 1)

In [ ]:
#building the model
from sklearn.tree import DecisionTreeRegressor
model = DecisionTreeRegressor()
model.fit(x_train, y_train)

In [ ]:
# Predicting the value
y_pred = model.predict(x_test)

In [ ]:
#Finding the rmse value
from sklearn.metrics import mean_squared_error
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
rmse

# Now we take multiple independent variable

In [ ]:
#Getting the feature and Target
x = pd.DataFrame(botson[['rm', 'lstat', 'age']]) # feature
y = pd.DataFrame(botson['medv']) # Target


In [ ]:
# Splitting the data into train and test
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.30)

In [ ]:
# Building the Model
from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeRegressor()
model.fit(x_train, y_train)

In [ ]:
# Predicting the values
y_pred = model.predict(x_test)

In [ ]:
#Finding the rmse value
from sklearn.metrics import mean_squared_error
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
rmse

Here we compared two model in which we can see RMSE value is lesser when multiple independent variable is taken, so we can say second model is better then first model.

# DecisionTreeClassifier Model

In [ ]:
# Import Libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

#Load Dataset
iris = pd.read_csv('/content/iris.csv')
iris

In [ ]:
# assign whole data for feature and only Species for target
x = pd.DataFrame(iris[['sepal_length', 'sepal_width', 'petal_length', 'petal_width']])
y = iris['species']

In [ ]:
iris.head()

In [ ]:
#Dividing the data into train and test
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.30)

In [ ]:
#Building decision Tree classifier
from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier()
model.fit(x_train, y_train)

In [ ]:
# Predict the model
y_pred = model.predict(x_test)

In [ ]:
# Confusion metrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score = accuracy_score(y_test, y_pred)
print(accuracy_score)

Based on the confusion matrix and accuracy score, here's I can infer about the Iris dataset and how the Decision Tree model performed on it:

High Accuracy: The accuracy_score of approximately 91.11% indicates that the model performed quite well overall in classifying the Iris species.

Confusion Matrix Analysis: Let's look at the confusion matrix:

[[15  0  0]
 [ 0 16  2]
 [ 0  2 10]]
First Class (e.g., Iris-setosa): The model perfectly classified the first class (likely Iris-setosa), with 15 correct predictions and zero misclassifications. This suggests that this species is very distinct and easily separable from the others based on the given features.

Second and Third Classes (e.g., Iris-versicolor and Iris-virginica): The misclassifications occurred primarily between the second and third classes:

2 instances that truly belonged to the second class were misclassified as the third class.
2 instances that truly belonged to the third class were misclassified as the second class.
This pattern of misclassification is common in the Iris dataset, as Iris-versicolor and Iris-virginica species are known to have some overlap in their sepal and petal measurements, making them slightly harder to distinguish than Iris-setosa.

In summary, the dataset appears to be relatively well-structured for classification, especially for the first class. The model effectively learned the distinctions, with the majority of errors occurring between the two less separable classes.